server:
  port: 8080
  servlet:
    context-path:

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java_sample_pos
    username: root
    password: ''

  jpa:
    hibernate:
      ddl-auto: none  # Keep your existing schema
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: false

app:
  jwtSecret: 6a565ec745d7355a72c7ed29cf5bca9e46aab58655b9941d70512b995a44a599
  jwtExpirationMs: 7776000000

logging:
  level:
    root: info
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Recommended CORS Configuration
cors:
  allowed-origins: "http://localhost:5666"
  allowed-methods: "*"
  allowed-headers: "*"
  allow-credentials: true
